apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "0 2 * * *"  # 每天凌晨2点执行
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodump
            image: mongo
            command: ["/bin/sh", "-c"]
            args: ["mongodump --uri mongodb://admin:password@mongo-svc:27017/mydatabase --archive=/backup/mydatabase.gz"]
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: backup-pvc

